<a href="https://colab.research.google.com/github/circuit-geek/Summer-Internship-2021/blob/main/Linear_Regression_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Gradient Descent and Linear Regression**

In this we will try to estimate the yield of Apple and oranges for the given parameters such as temperature, rainfall and humidity. The input values and the targets yield are given as numpy array.

In [1]:
import torch

In [11]:
input = torch.tensor([[73., 67., 43.],
                  [91., 88., 64.],
                  [87., 134., 58.],
                  [102., 43., 37.],
                  [69., 96., 70.]])

In [12]:
target = torch.tensor([[56.,70.],
                   [81.,101.],
                   [119.,133.],
                   [22.,37.],
                   [103.,119.]])

In [13]:
print(input.dtype, target.dtype)

torch.float32 torch.float32


Now that we have got our inputs and target values, we can train the model using linear regression, not just for tensorflow even for Pytorch the inputs could be as CSV files having the inputs and Targets.

In [14]:
#getting the weights and bias

w = torch.randn(2, 3 , requires_grad= True)
b = torch.randn(2 , requires_grad= True)
print(w,b)

tensor([[ 1.5018, -0.5976, -0.1544],
        [ 0.2167, -0.2155,  0.7817]], requires_grad=True) tensor([-0.1452,  0.5484], requires_grad=True)


In [15]:
def model(x):
  return x @ w.t() + b

We have defined a function called model which just computes the matrix values where "@" represents matrix multiplication and .t() function converts the matrix to its transpose. The return value gives the prediction when input variable is given as the function call to the model function.

In [16]:
preds = model(input)
print(preds)

tensor([[ 62.8066,  35.5412],
        [ 74.0468,  51.3314],
        [ 41.4739,  35.8624],
        [121.6289,  42.3073],
        [ 35.2996,  49.5300]], grad_fn=<AddBackward0>)


In [17]:
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


So from the predicted values and target values we understand the model is not performing very well as there is a significant difference between the two. So to understand how well they are performing we understand their loss function.

**Loss Function**


1.   Calculate the difference between the two matrices(preds and targets)
2.  Square all elements of the difference matrix to remove -ve values.
3.   Calculate the average of the resultant matrix.

This is know as Mean Square Error(MSE).

In [18]:
def mse(t1, t2):
  diff = t1-t2
  return torch.sum(diff*diff)/ diff.numel()

In [19]:
loss = mse(preds, target)
print(loss)

tensor(3855.8562, grad_fn=<DivBackward0>)


In [20]:
loss.backward() #calculating the gradients

In [21]:
print(w.grad)

tensor([[ -277.9632, -2551.9072, -1140.3195],
        [-3947.6785, -5227.3833, -2992.2056]])


In [22]:
print(b.grad)

tensor([ -9.1489, -49.0855])


When gradient values is positive then on increasing the weights the loss will increase and on descreasing the weights the loss will decrease, but when gradient values are negative on increasing the weight the loss will decrease and increase when the weight is decreased.

In [24]:
with torch.no_grad():
  w -= w.grad * 1e-5
  b -= b.grad * 1e-5

In [25]:
print(w,b)

tensor([[ 1.5046, -0.5721, -0.1430],
        [ 0.2562, -0.1632,  0.8116]], requires_grad=True) tensor([-0.1451,  0.5489], requires_grad=True)


In [26]:
new_preds = model(input)
loss = mse(new_preds, target)
print(loss)

tensor(3309.3523, grad_fn=<DivBackward0>)


In [28]:
 w.grad.zero_()
 b.grad.zero_()
 print(w.grad, b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([0., 0.])


After finishing with gradient calculations it is important to make the gradients zero as next time when call the backward() function the gradients keep accumulating.

In [30]:
#training the model for 100 epochs to even reduce the loss

for i in range(100):
  preds = model(input)
  loss = mse(preds, target)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

In [33]:
preds = model(input)
loss = mse(preds, target)
print(loss)

tensor(640.2341, grad_fn=<DivBackward0>)


In [34]:
print(preds)


tensor([[ 67.7508,  74.7119],
        [ 85.9406, 104.8542],
        [ 93.1828, 116.3661],
        [ 82.4086,  62.1936],
        [ 72.5981, 111.8318]], grad_fn=<AddBackward0>)


In [35]:
print(target)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
