<a href="https://colab.research.google.com/github/circuit-geek/Summer-Internship-2021/blob/main/Pytorch_and_Tensor_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Basics and Introduction to Tensors


In [1]:
import torch

In [2]:
t1 = torch.tensor(4.0)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor([[5., 6],
                   [7, 8],
                   [9 , 10]])
t2

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [6]:
t2.shape

torch.Size([3, 2])

Tensor Operations and Gradients

In [7]:
x = torch.tensor(3.)
w = torch.tensor(4. , requires_grad= True)
b = torch.tensor(5. , requires_grad= True)

print(x, w, b)

tensor(3.) tensor(4., requires_grad=True) tensor(5., requires_grad=True)


In [8]:
y = w*x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [9]:
y.backward()

In [10]:
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


The reason why, derivative of x is zero is the previously while assigning the tensor value for x we haven't specified the required grad parameter to be true.

Tensor Functions

In [11]:
t3 = torch.full((3,2), 42)
t3

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [13]:
t4 = torch.cat((t2,t3))
t4

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [14]:
t5 = torch.sin(t4)
t5

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [16]:
t6 = t5.reshape(3,2,2)
t6

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])